### ISSUE TITLE
pip install imatlab is out of date.

### ISSUE THREAD

**Issue by steverweber** [anntzer/imatlab#9]
```
10751]: [D 2017-03-27 10:25:07.661 JupyterHub systemdspawner:253] user:s8weber unit jupyter-s8weber-singleuser is active
 [I 2017-03-27 10:25:09.014 s8weber restarter:103] KernelRestarter: restarting kernel (1/5)
 WARNING:root:kernel 25edcaf3-7e38-4767-bb2f-cc4b3109c1cf restarted
 Traceback (most recent call last):
   File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
     "__main__", mod_spec)
   File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
     exec(code, run_globals)
   File "/usr/local/lib/python3.5/dist-packages/imatlab/__main__.py", line 5, in <module>
     IPKernelApp.launch_instance(kernel_class=MatlabKernel)
   File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 657, in launch_instance
     app.initialize(argv)
   File "<decorator-gen-120>", line 2, in initialize
   File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
     return method(app, *args, **kwargs)
   File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelapp.py", line 454, in initialize
     self.init_kernel()
   File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelapp.py", line 365, in init_kernel
     user_ns=self.user_ns,
   File "/usr/local/lib/python3.5/dist-packages/traitlets/config/configurable.py", line 412, in instance
     inst = cls(*args, **kwargs)
   File "/usr/local/lib/python3.5/dist-packages/imatlab/_kernel.py", line 119, in __init__
     Path(self._call("prefdir"), "History.xml"))
   File "/usr/local/lib/python3.5/dist-packages/imatlab/_kernel.py", line 37, in __init__
     self._et = ET.parse(str(path))
   File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 1184, in parse
     tree.parse(source, parser)
   File "/usr/lib/python3.5/xml/etree/ElementTree.py", line 585, in parse
     source = open(source, "rb")
 FileNotFoundError: [Errno 2] No such file or directory: '/u/s8weber/.matlab/R2016b/History.xml'
 Assertion failed: nbytes == size
```

after updating my _kernel.py that was installed using `pip` with your current copy in the repo. got the kernel working.

so please push the latest code to pip so others like me don't fail :)

**Comment by imatlab-helper** [comment]
Thanks @steverweber. This error affects people running without the matlab GUI (since no History.xml file is created) and was fixed a few weeks ago in the repo. There are a few loose ends we are working on before pushing out the next release to PyPI. Namely: plotly/MATLAB-Online#118, https://github.com/anntzer/imatlab/issues/6#issuecomment-289318544, and https://github.com/anntzer/imatlab/issues/6#issuecomment-287859541.

**Comment by anntzer** [comment]
Thanks @imatlab-helper for handling this.
In order to install the git version, either follow in instructions in the README, or https://github.com/anntzer/imatlab/issues/2#issuecomment-284005633 if you don't have git.
